- name: install wget
  package:
        name: wget  
        state: present
- name: create yum directory
  file:
        path: "{{yum.path}}"
        state: directory
- name: get jenkins
  apt_repository:
        repo: "{{jenkins.deb_url}}"
        state: present




- name: install jenkins
  package:
      name: jenkins
      state: present
  
