- name: install wget
  package:
        name: wget  
        state: present
- name: create yum directory
  file:
        path: "{{yum.path}}"
        state: directory
- name: get jenkins
  yum_repository:
        name: jenkins
        description: a jenkins yum repository
        baseurl: "{{jenkins.url}}"
        gpgcheck: yes 
        gpgkey: "{{yum.key}}"



- name: install jenkins
  yum:
      name: jenkins
      state: present
  
