- name: install wget
  package:
        name: wget  
        state: present
- name: create yum directory
  file:
        path: "{{yum.path}}"
        state: directory

- name: Add Jenkins apt repository key.
  apt_key:
    url: "{{ jenkins.deb_url_key }}"
    state: present
- name: get jenkins
  apt_repository:
        repo: "{{jenkins.deb_url}}"
        state: present




- name: install jenkins
  package:
      name: jenkins
      state: present
  
