- name: Ensure dependencies are installed.
  apt:
    name:
      - curl
      - apt-transport-https
      - gnupg
    state: present


- name: install wget
  package:
        name: wget  
        state: present
- name: create yum directory
  file:
        path: "{{yum.path}}"
        state: directory

- name: Add Jenkins apt repository key.
  apt_key:
    url: "{{ jenkins.deb_url_key }}"
    state: present
- name: get jenkins
  apt_repository:
        repo: "{{jenkins.deb_url}}"
        state: present

- name: update and upgrade packages
  apt:
      upgrade: dist
      name: "*"
      state: latest
- name: install jenkins
  apt:
      name: jenkins
      state: present
  
- name: jenkins starting
  service:
      name: jenkins
      state: started
      enabled : yes
  
