- name : Removing other java version
  package:
      name: java
      state: absent

- name : Adding java 1.8 
  package:
      name: "{{java.version}}"
      state: present
  loop:
    - openjdk-8-jdk


